Added docker compose file to use artifact registry and new deployment
cznethub/cznet-discovery pull request #33
Opened 2024-07-23 14:06 UTC by jnsproul

2024-07-23 19:44 UTC, cbcunc requested changes

2024-07-23 19:44 UTC, cbcunc commented on docker-compose-artifact-registry.yml
> +version: "3.8"
```suggestion
```

2024-07-23 19:44 UTC, cbcunc commented on docker-compose-artifact-registry.yml
> +
```suggestion
```

2024-07-23 19:44 UTC, cbcunc commented on docker-compose-artifact-registry.yml
> +version: "3.8"
`version` has been deprecated.

2024-07-23 19:44 UTC, cbcunc commented on docker-compose-artifact-registry.yml
Have you tested this? it looks fine except for the minor shakes I suggested.

2024-07-23 19:46 UTC, cbcunc commented
We'll probably want to make the URI for AR an environment variable later. But just leave it be for now.

2024-09-10 15:31 UTC, jnsproul commented on docker-compose-artifact-registry.yml
Tested

2024-09-10 15:32 UTC, jnsproul commented
All requested changes have been made this can go in whenever

2024-09-30 15:00 UTC, merged